apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  namespace: gecko-eats
  labels:
    app: bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: bot
      labels:
        app: bot
    spec:
      containers:
        - name: bot
          image: docker.io/qrave1/gecko-eats:a649bc5
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "10Mi"
            limits:
              memory: "300Mi"
          envFrom:
            - configMapRef:
                name: bot
      restartPolicy: Always
      