apiVersion: batch/v1
kind: CronJob
metadata:
  name: notify
  namespace: gecko-eats
spec:
  schedule: "* 9,22 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        spec:
          containers:
            - name: notify
              image: docker.io/qrave1/gecko-eats:8249935
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  memory: "50Mi"
              envFrom:
                - configMapRef:
                    name: bot
              command:
                - /app/build
                - notify
          restartPolicy: OnFailure