apiVersion: batch/v1
kind: CronJob
metadata:
  name: notify
  namespace: gecko-eats
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: notify
              image: docker.io/qrave1/gecko-eats:b771a82
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  memory: "10Mi"
                limits:
                  memory: "300Mi"
              envFrom:
                - configMapRef:
                    name: bot
              command:
                - /app/build
                - notify
          restartPolicy: OnFailure