// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/qrave1/gecko-eats/cmd/provider"
)

// Injectors from wire.go:

func InitializeBotService(contextContext context.Context, string2 string) (*provider.BotService, error) {
	config, err := provider.ProvideConfig()
	if err != nil {
		return nil, err
	}
	bot, err := provider.ProvideTeleBot(config)
	if err != nil {
		return nil, err
	}
	db, err := provider.ProvideSQLXConnection(config)
	if err != nil {
		return nil, err
	}
	repository := provider.ProvideRepository(config, db)
	botServer, err := provider.ProvideBotServer(bot, repository, config)
	if err != nil {
		return nil, err
	}
	botService := provider.ProvideBotService(contextContext, botServer)
	return botService, nil
}

func InitializeNotifyService(contextContext context.Context, string2 string) (*provider.NotifyService, error) {
	config, err := provider.ProvideConfig()
	if err != nil {
		return nil, err
	}
	bot, err := provider.ProvideTeleBot(config)
	if err != nil {
		return nil, err
	}
	db, err := provider.ProvideSQLXConnection(config)
	if err != nil {
		return nil, err
	}
	repository := provider.ProvideRepository(config, db)
	notifier := provider.ProvideNotifier(bot, repository, config)
	notifyService := provider.ProvideNotifyService(notifier)
	return notifyService, nil
}
