name: Build & Deploy with Telegram Notifications

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to perform"
        required: true
        default: "build"
        type: choice
        options:
          - build
          - deploy
          - rollback

jobs:
  manual-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Makefile target
        id: deploy_step
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${VPS_SSH_KEY}" > id_rsa
          chmod 600 id_rsa
          export SSH_AUTH_SOCK=
          export GIT_SSH_COMMAND="ssh -i ./id_rsa -o StrictHostKeyChecking=no"

          make ${{ github.event.inputs.action }}

      - name: Notify Telegram (Success)
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✅ [${{ github.event.inputs.action }}] успешно завершена!
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Автор: ${{ github.actor }}
            Коммит: ${{ github.sha }}

      - name: Notify Telegram (Failure)
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ❌ Ошибка на этапе [${{ github.event.inputs.action }}]!
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref_name }}
            Автор: ${{ github.actor }}
            Коммит: ${{ github.sha }}
